TASK 1: API INTEGRATION AND DATA VISUALIZATION

COMPANY: CODTECH IT SOLUTIONS

NAME:AR.DEIVANAI

INTERN ID:CT08NDM

DOMAIN:Python Programming

BATCH DURATION:  January 15th, 2025 to February 15th, 2025  

MENTOR NAME: NEELA SANTHOSH

DESCRIPTION OF TASK PERFORMED:
